// What this script does:
// Crawl through each subfolder in the folders listed in `directoriesToProcess`
// then automatically export everything from those subfolders to
// 'index.scripted.ts'.

import chalk from 'chalk'
import * as fs from 'fs'
import { ENCODING_UTF_8 } from '../../constants'

const CORE = [ // TODO
  './src',
  './src/cli',
  './src/dom',
  './src/data',
  './src/data/array',
  './src/data/object',
  './src/datetime',
  './src/encoding',
  './src/events',
  './src/function',
  './src/hash',
  './src/math',
  './src/music',
  './src/network',
  './src/promise',
  './src/random',
  './src/react',
  './src/react/components',
  './src/react/core-ui',
  './src/react/hooks',
  './src/react/special',
  './src/string',
  './src/styling',
  './src/web-monetization',
]

export function autoForwardExports(directoriesToProcess: Array<string>): void {

  for (let i = 0; i < directoriesToProcess.length; i++) {
    processDirectory(directoriesToProcess[i])
  }

  function processDirectory(path: string): void {
    const rawItemStack = fs.readdirSync(path, ENCODING_UTF_8)
    const now = new Date()
    const codeLineStack = [
      '// Please do not edit here.',
      '// This file was automatically generated by the script `yarn fwd-exp`.',
      '// To learn more, refer to `scripts/run/auto-forward-exports`',
      '',
    ]
    let forwardedItemsCount = 0
    for (let i = 0; i < rawItemStack.length; i++) {
      if (
        // Ignore if contains dots (only files have extensions)
        // '*.draft' files will also be ignored
        !/\./g.test(rawItemStack[i]) &&
        // Ignore if has '__...__' naming pattern
        !/^__.+__$/.test(rawItemStack[i])
      ) {
        let item = rawItemStack[i]
        if (item === 'abstractions' || item === 'constants') { item += '/public' }
        codeLineStack.push(`export * from './${item}'`)
        forwardedItemsCount += 1
      }
    }
    codeLineStack.push(
      `\n// Last updated: ${now.toDateString()} ${now.toTimeString().match(/\d{2}:\d{2}:\d{2} [a-z]+\+\d{4}/i)[0]}.`,
    )
    fs.writeFileSync(
      `${path}/index.scripted.ts`,
      codeLineStack.join('\n') + '\n',
      ENCODING_UTF_8,
    )
    console.log(
      ' • Forwarded ' +
      chalk.cyan(`${forwardedItemsCount.toString().padStart(2, ' ')} item${forwardedItemsCount !== 1 ? 's' : ' '}`) +
      ' to ' +
      chalk.cyan(path) +
      chalk.gray('/index.scripted.ts')
    )
  }

}
