// cspell:words networkidle2 ngcontent nghost

// import fs from 'node:fs'
import puppeteer, { Page } from 'puppeteer'

async function run(): Promise<void> {

  console.info('Initializing...')
  const browser = await puppeteer.launch({ slowMo: 500, headless: false })
  const page = await browser.newPage()

  console.info('Launching Material Icons page...')
  const targetUrl = 'https://fonts.google.com/icons?icon.set=Material+Symbols'
  await page.goto(targetUrl, { waitUntil: 'networkidle2' })

  // This is how the page is structured and how it can be navigated as of 02 Sep 2024.

  console.info('Scrolling through the page...')
  await scrollToPageBottom(page)
  await page.waitForSelector('#main-content > div > div > gf-icons > div > icons-page > icons-group:last-child')

  console.info('Getting icon names...')
  let fetchedIconNames = await page.evaluate(() => {
    const arr: Array<string> = []
    // <gf-load-icon-font _ngcontent-ng-c651786718="" _nghost-ng-c1526427138="" class="">view_object_track</gf-load-icon-font>
    // #main-content > div > div > gf-icons > div > icons-page > icons-group:nth-child(18) > div > button.ng-star-inserted > span.icon-asset.material-symbols-outlined > gf-load-icon-font
    // const stack = document.querySelectorAll('button[class="ng-star-inserted"] > span > span')
    const stack = document.querySelectorAll('gf-load-icon-font')
    for (const item of stack) {
      arr.push(item.textContent)
    }
    return arr
  })

  console.info('Closing browser...')
  await page.close()
  await browser.close()

  // console.log({ fetchedIconNames })
  if (fetchedIconNames.length <= 0) {
    throw new Error('Unable to find any icons')
  }

  console.info('Normalizing retrieved data...')
  fetchedIconNames = [...new Set(fetchedIconNames)]
  fetchedIconNames.sort()
  const quotedIconNameStack = fetchedIconNames.map((icon) => `'${icon}'`)

  // const fileTitle = './src/packages/react/src/material-symbols/names.ts'
  // console.info(`Writing to '${fileTitle}'...`)
  const now = new Date()
  const bullet = '  | '
  const docBlock = [
    '/**',
    ` * Last updated: ${now.toDateString()} ${now.toTimeString()}`,
    ' * @public',
    ' */',
  ].join('\n')
  const fileBody = [
    '/* eslint-disable */',
    '// cspell:disable',
    '// DO NOT MODIFY - THIS FILE IS AUTOMATICALLY GENERATED',
    '// This file was automatically generated by the script `yarn bot:muicon`.',
    '// To learn more, refer to `scripts/run/fetch-material-symbol-names`',
    '', // (Empty line)
    'import { LenientString } from \'@glyph-cat/foundation\'',
    '', // (Empty line)
    docBlock,
    'export type MaterialSymbolName = LenientString<StrictMaterialSymbolName>',
    '', // (Empty line)
    docBlock,
    'export type StrictMaterialSymbolName =',
    bullet + quotedIconNameStack.join(`\n${bullet}`),
    '', // (Empty line)
  ].join('\n')
  // console.log('=== fileTitle ===')
  // console.log(fileTitle)
  // console.log('=== fileBody ===')
  console.clear()
  console.log('='.repeat(20))
  console.log(fileBody)
  console.log('='.repeat(20))
  // fs.writeFileSync(fileTitle, fileBody, 'utf-8')

}

run()

/**
 * @see https://stackoverflow.com/a/67829516/5810737
 */
async function scrollToPageBottom(page: Page): Promise<void> {
  await page.evaluate(async () => {
    let scrollPosition = 0
    let documentHeight = document.body.scrollHeight
    while (documentHeight > scrollPosition) {
      window.scrollBy(0, documentHeight)
      await new Promise<void>(resolve => {
        setTimeout(() => { resolve() }, 500)
      })
      scrollPosition = documentHeight
      documentHeight = document.body.scrollHeight
    }
  })
}
