import { readFileSync, writeFileSync } from 'fs'
import { ENCODING_UTF_8 } from '../../constants'

export function run(): void {

  const codeLineStack = [
    '// Please do not edit here.',
    '// This file was automatically generated by the script `yarn css-enums`.',
    '// To learn more, refer to `scripts/run/css-enums`',
    '',
    'export enum TemplateStyles {',
  ]

  const cssContents = readFileSync('./src/styling/templates/index.module.css', ENCODING_UTF_8)
  const classNames = cssContents.split(/\n/g)
    .filter((line) => /^\..+{$/.test(line))
    .map((line) => line.replace(/^\./, '').replace(/^\./, '').replace(/\s*{$/, ''))
  // KIV: This does not take ids(#...), pseudo classes, selectors, and nested classnames
  // into consideration.

  for (const className of classNames) {
    codeLineStack.push(`  ${className} = '${className}',`)
  }

  const now = new Date()

  codeLineStack.push(
    '}',
    '',
    `// Generated on: ${now.toDateString()} ${now.toTimeString().match(/\d{2}:\d{2}:\d{2} [a-z]+\+\d{4}/i)[0]}.`,
  )

  writeFileSync(
    './src/styling/templates/abstractions.scripted.ts',
    codeLineStack.join('\n') + '\n',
    ENCODING_UTF_8,
  )

}

run()
