// What this script does:
// Crawl through each subfolder in the folders listed in `directoriesToProcess`
// then automatically export everything from those subfolders to
// 'index.scripted.ts'.

import * as chalk from 'chalk'
import * as fs from 'fs'

const directoriesToProcess = [
  './src',
  './src/dom',
  './src/data',
  './src/data/array',
  './src/data/object',
  './src/datetime',
  './src/events',
  './src/function',
  './src/hash',
  './src/math',
  './src/promise',
  './src/random',
  './src/react',
  './src/react/components',
  './src/react/core-ui',
  './src/react/hooks',
  './src/react/special',
  './src/string',
  './src/styling',
  './src/web-monetization',
]

for (let i = 0; i < directoriesToProcess.length; i++) {
  autoForwardExports(directoriesToProcess[i])
}

function autoForwardExports(path: string): void {
  const rawItemStack = fs.readdirSync(path, { encoding: 'utf-8' })
  const now = new Date()
  const codeLineStack = [
    '// Please do not edit here.',
    '// This file was automatically generated by the script `yarn fwd-exp`.',
    '// To learn more, refer to `scripts/auto-forward-exports`',
    '',
  ]
  let forwardedItemsCount = 0
  for (let i = 0; i < rawItemStack.length; i++) {
    if (
      // Ignore if contains dots (only files have extensions)
      // '*.draft' files will also be ignored
      !/\./g.test(rawItemStack[i]) &&
      // Ignore if has '__...__' naming pattern
      !/^__.+__$/.test(rawItemStack[i])
    ) {
      let item = rawItemStack[i]
      if (item === 'constants') { item += '/public' }
      codeLineStack.push(`export * from './${item}'`)
      forwardedItemsCount += 1
    }
  }
  codeLineStack.push(
    `\n// Last updated: ${now.toDateString()} ${now.toTimeString()}.`,
  )
  fs.writeFileSync(
    `${path}/index.scripted.ts`,
    codeLineStack.join('\n') + '\n',
    { encoding: 'utf-8' }
  )
  console.log(
    ' • Forwarded ' +
    chalk.cyan(`${forwardedItemsCount.toString().padStart(2, ' ')} item${forwardedItemsCount !== 1 ? 's' : ' '}`) +
    ' to ' +
    chalk.cyan(path) +
    chalk.gray('/index.scripted.ts')
  )
}
